# Generated by Django 2.1.2 on 2018-10-18 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
