# Generated by Django 2.1.2 on 2018-10-18 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_auto_20181018_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
